import os

# --- 配置 ---
# 源目录：OCCT 的 'inc' 文件夹路径
OCCT_INC_PATH = r'D:\OCCT\opencascade-7.9.2-vc14-64\inc'

# 输出文件：将要生成的头文件列表
OUTPUT_FILE = 'class_list_all.txt'

# 要查找的头文件扩展名
HEADER_EXTENSIONS = ('.hxx', '.h')


def generate_header_list():
    """
    遍历指定目录，查找所有头文件，并将其相对路径写入输出文件。
    """
    # 确保源路径存在且是一个目录
    if not os.path.isdir(OCCT_INC_PATH):
        print(f"错误：源目录不存在或不是一个有效的目录 -> {OCCT_INC_PATH}")
        return

    print(f"正在扫描目录: {OCCT_INC_PATH}...")

    header_files = []
    # os.walk() 会递归地遍历目录树
    for root, dirs, files in os.walk(OCCT_INC_PATH):
        for file in files:
            # 检查文件扩展名是否是我们想要的头文件类型
            if file.endswith(HEADER_EXTENSIONS):
                # 获取文件的完整路径
                full_path = os.path.join(root, file)

                # 计算相对于 OCCT_INC_PATH 的路径
                relative_path = os.path.relpath(full_path, OCCT_INC_PATH)

                # 为了跨平台兼容性和 #include 语法的标准，将路径分隔符统一为 '/'
                relative_path = relative_path.replace(os.sep, '/')

                header_files.append(relative_path)

    if not header_files:
        print("未找到任何头文件。")
        return

    # 按字母顺序排序，使列表更整洁
    header_files.sort()

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            # (可选) 在文件顶部添加一个注释头
            f.write("# Auto-generated list of OCCT header files to be processed.\n")
            f.write("# Generated by generate_class_list.py\n\n")

            # 逐行写入文件路径
            for path in header_files:
                f.write(f"{path}\n")

        print("-" * 50)
        print(f"成功！共找到 {len(header_files)} 个头文件。")
        print(f"列表已写入文件: {os.path.abspath(OUTPUT_FILE)}")
        print("-" * 50)

    except Exception as e:
        print(f"写入文件时发生错误: {e}")


if __name__ == '__main__':
    generate_header_list()
