// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-11 16:25:23.893044

#include "ManualReflection.h"
#include "ReflectionAccessor.h"

// We must include the headers to have the full type definitions
#include <gp_Pnt.hxx>
#include <gp_Lin.hxx>
#include <gp_XYZ.hxx>
#include <gp_Ax1.hxx>

// Implementation of the initialization function declared in ManualReflection.h
void initialize_reflection() {
    auto& registry = ReflectionRegistry::instance();

    // --- Registering gp_Pnt ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Pnt";
        desc.neo4j_label = "gp_Pnt";
        {
            PropertyDescriptor prop;
            prop.name = "coord";
            prop.type_name = "::gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Pnt&>(obj_any);
                return ReflectionAccessor::get_gp_Pnt_coord(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Pnt&>(obj_any);
                const auto& val = std::any_cast<const ::gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Pnt_coord(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_XYZ";
            desc.properties["coord"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Ax1 ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Ax1";
        desc.neo4j_label = "gp_Ax1";
        {
            PropertyDescriptor prop;
            prop.name = "loc";
            prop.type_name = "::gp_Pnt";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return ReflectionAccessor::get_gp_Ax1_loc(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Pnt&>(val_any);
                ReflectionAccessor::set_gp_Ax1_loc(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_PNT";
            desc.properties["loc"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vdir";
            prop.type_name = "::gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return ReflectionAccessor::get_gp_Ax1_vdir(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax1_vdir(obj, val);
            };
            desc.properties["vdir"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_XYZ ---
    {
        TypeDescriptor desc;
        desc.name = "gp_XYZ";
        desc.neo4j_label = "gp_XYZ";
        {
            PropertyDescriptor prop;
            prop.name = "x";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return ReflectionAccessor::get_gp_XYZ_x(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_x(obj, val);
            };
            desc.properties["x"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "y";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return ReflectionAccessor::get_gp_XYZ_y(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_y(obj, val);
            };
            desc.properties["y"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "z";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return ReflectionAccessor::get_gp_XYZ_z(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_z(obj, val);
            };
            desc.properties["z"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Lin ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Lin";
        desc.neo4j_label = "gp_Lin";
        {
            PropertyDescriptor prop;
            prop.name = "pos";
            prop.type_name = "::gp_Ax1";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Lin&>(obj_any);
                return ReflectionAccessor::get_gp_Lin_pos(obj);
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Lin&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Ax1&>(val_any);
                ReflectionAccessor::set_gp_Lin_pos(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_AX1";
            desc.properties["pos"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }
}