// Generated by Tooling/generate_reflection.py (Heuristic Engine)
// Timestamp: 2025-11-14 22:16:47.028848

#include "ManualReflection.h"
#include "ReflectionAccessor.h"
#include "OCCTSerializer.h"

// Headers for reflected types
#include <gp_Pnt.hxx>
#include <gp_Dir.hxx>
#include <gp_Vec.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Ax3.hxx>
#include <gp_XYZ.hxx>
#include <gp_Trsf.hxx>
#include <gp_Quaternion.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_CompSolid.hxx>
#include <TopoDS_Compound.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Line.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_Hyperbola.hxx>
#include <Geom_Parabola.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_Surface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_BezierSurface.hxx>
#include <TopLoc_Location.hxx>

// Headers required by heuristic handlers
#include "OCCTValueConverter.h"
#include <BRep_Tool.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Surface.hxx>
#include <TopLoc_Location.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Vertex.hxx>

// Auto-generated heuristic handler for TopoDS_Shape
void handle_TopoDS_Shape_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Shape&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

// Auto-generated heuristic handler for TopoDS_Vertex
void handle_TopoDS_Vertex_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Vertex&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());


    gp_Pnt pnt = BRep_Tool::Pnt(specific_shape);
    node.properties["geometry"] = OCCTValueConverter::to_serializable(std::any(pnt));

}

// Auto-generated heuristic handler for TopoDS_Edge
void handle_TopoDS_Edge_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Edge&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());


    Standard_Real first, last;
    Handle(Geom_Curve) curve = BRep_Tool::Curve(specific_shape, first, last);
    serializer.serialize_transient_and_link(curve, node.temp_id, "GEOMETRY");
    node.properties["range_first"] = first;
    node.properties["range_last"] = last;

}

// Auto-generated heuristic handler for TopoDS_Wire
void handle_TopoDS_Wire_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Wire&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

// Auto-generated heuristic handler for TopoDS_Face
void handle_TopoDS_Face_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Face&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());


    Handle(Geom_Surface) surface = BRep_Tool::Surface(specific_shape);
    serializer.serialize_transient_and_link(surface, node.temp_id, "GEOMETRY");

}

// Auto-generated heuristic handler for TopoDS_Shell
void handle_TopoDS_Shell_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Shell&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

// Auto-generated heuristic handler for TopoDS_Solid
void handle_TopoDS_Solid_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Solid&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

// Auto-generated heuristic handler for TopoDS_CompSolid
void handle_TopoDS_CompSolid_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_CompSolid&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

// Auto-generated heuristic handler for TopoDS_Compound
void handle_TopoDS_Compound_serialization(const std::any& obj_any, OCCTSerializer& serializer, IntermediateNode& node) {

    const auto& specific_shape = std::any_cast<const TopoDS_Compound&>(obj_any);
    const TopoDS_Shape& shape = specific_shape;
    TopLoc_Location location = shape.Location();
    if (!location.IsIdentity()) {
        serializer.serialize_transient_and_link(location.FirstDatum(), node.temp_id, "HAS_LOCATION");
    }
    node.properties["orientation"] = static_cast<int32_t>(shape.Orientation());

}

void initialize_reflection() {
    auto& registry = ReflectionRegistry::instance();

    // --- Registering gp_Pnt ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Pnt";
        desc.neo4j_label = "gp_Pnt";
        {
            PropertyDescriptor prop;
            prop.name = "coord";
            prop.type_name = "gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Pnt&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Pnt_coord(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Pnt&>(obj_any);
                const auto& val = std::any_cast<const gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Pnt_coord(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["coord"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Dir ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Dir";
        desc.neo4j_label = "gp_Dir";
        {
            PropertyDescriptor prop;
            prop.name = "coord";
            prop.type_name = "gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Dir&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Dir_coord(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Dir&>(obj_any);
                const auto& val = std::any_cast<const gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Dir_coord(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["coord"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Ax1 ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Ax1";
        desc.neo4j_label = "gp_Ax1";
        {
            PropertyDescriptor prop;
            prop.name = "loc";
            prop.type_name = "gp_Pnt";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax1_loc(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const gp_Pnt&>(val_any);
                ReflectionAccessor::set_gp_Ax1_loc(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["loc"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vdir";
            prop.type_name = "gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax1_vdir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax1_vdir(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["vdir"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Ax2 ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Ax2";
        desc.neo4j_label = "gp_Ax2";
        {
            PropertyDescriptor prop;
            prop.name = "axis";
            prop.type_name = "gp_Ax1";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax2&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax2_axis(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax2&>(obj_any);
                const auto& val = std::any_cast<const gp_Ax1&>(val_any);
                ReflectionAccessor::set_gp_Ax2_axis(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_AX1";
            desc.properties["axis"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vydir";
            prop.type_name = "gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax2&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax2_vydir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax2&>(obj_any);
                const auto& val = std::any_cast<const gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax2_vydir(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["vydir"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vxdir";
            prop.type_name = "gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax2&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax2_vxdir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax2&>(obj_any);
                const auto& val = std::any_cast<const gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax2_vxdir(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["vxdir"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_XYZ ---
    {
        TypeDescriptor desc;
        desc.name = "gp_XYZ";
        desc.neo4j_label = "gp_XYZ";
        {
            PropertyDescriptor prop;
            prop.name = "x";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_x(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_x(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["x"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "y";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_y(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_y(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["y"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "z";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_z(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_z(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["z"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Trsf ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Trsf";
        desc.neo4j_label = "gp_Trsf";
        {
            PropertyDescriptor prop;
            prop.name = "scale";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Trsf&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Trsf_scale(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Trsf&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_Trsf_scale(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["scale"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "shape";
            prop.type_name = "gp_TrsfForm";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Trsf&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Trsf_shape(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Trsf&>(obj_any);
                const auto& val = std::any_cast<const gp_TrsfForm&>(val_any);
                ReflectionAccessor::set_gp_Trsf_shape(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_TRSFFORM";
            desc.properties["shape"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "atrix";
            prop.type_name = "gp_Mat";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Trsf&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Trsf_matrix(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Trsf&>(obj_any);
                const auto& val = std::any_cast<const gp_Mat&>(val_any);
                ReflectionAccessor::set_gp_Trsf_matrix(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_MAT";
            desc.properties["atrix"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "loc";
            prop.type_name = "gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Trsf&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Trsf_loc(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Trsf&>(obj_any);
                const auto& val = std::any_cast<const gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Trsf_loc(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["loc"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Vec ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Vec";
        desc.neo4j_label = "gp_Vec";
        {
            PropertyDescriptor prop;
            prop.name = "coord";
            prop.type_name = "gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Vec&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Vec_coord(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Vec&>(obj_any);
                const auto& val = std::any_cast<const gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Vec_coord(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["coord"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Quaternion ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Quaternion";
        desc.neo4j_label = "gp_Quaternion";
        {
            PropertyDescriptor prop;
            prop.name = "x";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Quaternion&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Quaternion_x(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Quaternion&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_Quaternion_x(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["x"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "y";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Quaternion&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Quaternion_y(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Quaternion&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_Quaternion_y(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["y"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "z";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Quaternion&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Quaternion_z(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Quaternion&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_Quaternion_z(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["z"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "w";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Quaternion&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Quaternion_w(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Quaternion&>(obj_any);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_Quaternion_w(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["w"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Ax3 ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Ax3";
        desc.neo4j_label = "gp_Ax3";
        {
            PropertyDescriptor prop;
            prop.name = "axis";
            prop.type_name = "gp_Ax1";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax3&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax3_axis(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax3&>(obj_any);
                const auto& val = std::any_cast<const gp_Ax1&>(val_any);
                ReflectionAccessor::set_gp_Ax3_axis(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_AX1";
            desc.properties["axis"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vydir";
            prop.type_name = "gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax3&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax3_vydir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax3&>(obj_any);
                const auto& val = std::any_cast<const gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax3_vydir(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["vydir"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vxdir";
            prop.type_name = "gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax3&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax3_vxdir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax3&>(obj_any);
                const auto& val = std::any_cast<const gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax3_vxdir(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["vxdir"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopLoc_Location ---
    {
        TypeDescriptor desc;
        desc.name = "TopLoc_Location";
        desc.neo4j_label = "TopLoc_Location";
        {
            PropertyDescriptor prop;
            prop.name = "Items";
            prop.type_name = "TopLoc_SListOfItemLocation";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopLoc_Location&>(obj_any);
                return std::any(ReflectionAccessor::get_TopLoc_Location_myItems(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopLoc_Location&>(obj_any);
                const auto& val = std::any_cast<const TopLoc_SListOfItemLocation&>(val_any);
                ReflectionAccessor::set_TopLoc_Location_myItems(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TOPLOC_SLISTOFITEMLOCATION";
            desc.properties["Items"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Shape ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Shape";
        desc.neo4j_label = "TopoDS_Shape";
        desc.relationship_name_as_child = "HAS_SHAPE";
        {
            PropertyDescriptor prop;
            prop.name = "TShape";
            prop.type_name = "opencascade::handle<TopoDS_TShape>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myTShape(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const opencascade::handle<TopoDS_TShape>&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myTShape(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TOPODS_TSHAPE";
            desc.properties["TShape"] = std::move(prop);
        }
        desc.relationship_name_as_child = "HAS_SHAPE";
        {
            PropertyDescriptor prop;
            prop.name = "Location";
            prop.type_name = "TopLoc_Location";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myLocation(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const TopLoc_Location&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myLocation(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["Location"] = std::move(prop);
        }
        desc.relationship_name_as_child = "HAS_SHAPE";
        {
            PropertyDescriptor prop;
            prop.name = "Orient";
            prop.type_name = "TopAbs_Orientation";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myOrient(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const TopAbs_Orientation&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myOrient(obj, val);
            };
            prop.is_relationship = false;
            desc.properties["Orient"] = std::move(prop);
        }
        desc.special_handler = &handle_TopoDS_Shape_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Vertex ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Vertex";
        desc.neo4j_label = "TopoDS_Vertex";
        desc.special_handler = &handle_TopoDS_Vertex_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Edge ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Edge";
        desc.neo4j_label = "TopoDS_Edge";
        desc.special_handler = &handle_TopoDS_Edge_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Wire ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Wire";
        desc.neo4j_label = "TopoDS_Wire";
        desc.special_handler = &handle_TopoDS_Wire_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Face ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Face";
        desc.neo4j_label = "TopoDS_Face";
        desc.special_handler = &handle_TopoDS_Face_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Shell ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Shell";
        desc.neo4j_label = "TopoDS_Shell";
        desc.special_handler = &handle_TopoDS_Shell_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Solid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Solid";
        desc.neo4j_label = "TopoDS_Solid";
        desc.special_handler = &handle_TopoDS_Solid_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_CompSolid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_CompSolid";
        desc.neo4j_label = "TopoDS_CompSolid";
        desc.special_handler = &handle_TopoDS_CompSolid_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Compound ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Compound";
        desc.neo4j_label = "TopoDS_Compound";
        desc.special_handler = &handle_TopoDS_Compound_serialization;
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Curve ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Curve";
        desc.neo4j_label = "Geom_Curve";
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Line ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Line";
        desc.neo4j_label = "Geom_Line";
        {
            PropertyDescriptor prop;
            prop.name = "pos";
            prop.type_name = "gp_Ax1";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Line&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Line_pos(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Line&>(*base_ptr);
                const auto& val = std::any_cast<const gp_Ax1&>(val_any);
                ReflectionAccessor::set_Geom_Line_pos(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_AX1";
            desc.properties["pos"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Circle ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Circle";
        desc.neo4j_label = "Geom_Circle";
        {
            PropertyDescriptor prop;
            prop.name = "radius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Circle&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Circle_radius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Circle&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Circle_radius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["radius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Ellipse ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Ellipse";
        desc.neo4j_label = "Geom_Ellipse";
        {
            PropertyDescriptor prop;
            prop.name = "ajorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Ellipse&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Ellipse_majorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Ellipse&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Ellipse_majorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["ajorRadius"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "inorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Ellipse&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Ellipse_minorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Ellipse&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Ellipse_minorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["inorRadius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Hyperbola ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Hyperbola";
        desc.neo4j_label = "Geom_Hyperbola";
        {
            PropertyDescriptor prop;
            prop.name = "ajorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Hyperbola&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Hyperbola_majorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Hyperbola&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Hyperbola_majorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["ajorRadius"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "inorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Hyperbola&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Hyperbola_minorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Hyperbola&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Hyperbola_minorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["inorRadius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Parabola ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Parabola";
        desc.neo4j_label = "Geom_Parabola";
        {
            PropertyDescriptor prop;
            prop.name = "focalLength";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_Parabola&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_Parabola_focalLength(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_Parabola&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_Parabola_focalLength(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["focalLength"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_BSplineCurve ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_BSplineCurve";
        desc.neo4j_label = "Geom_BSplineCurve";
        {
            PropertyDescriptor prop;
            prop.name = "rational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_rational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_rational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["rational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "periodic";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_periodic(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_periodic(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["periodic"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "knotSet";
            prop.type_name = "GeomAbs_BSplKnotDistribution";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_knotSet(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_BSplKnotDistribution&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_knotSet(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_BSPLKNOTDISTRIBUTION";
            desc.properties["knotSet"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "smooth";
            prop.type_name = "GeomAbs_Shape";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_smooth(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_Shape&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_smooth(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_SHAPE";
            desc.properties["smooth"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "deg";
            prop.type_name = "int";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_deg(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Integer&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_deg(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_INT";
            desc.properties["deg"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "poles";
            prop.type_name = "opencascade::handle<TColgp_HArray1OfPnt>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_poles(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColgp_HArray1OfPnt>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_poles(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLGP_HARRAY1OFPNT";
            desc.properties["poles"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "weights";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_weights(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_weights(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["weights"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "flatknots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_flatknots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_flatknots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["flatknots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "knots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_knots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_knots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["knots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "ults";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfInteger>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_mults(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfInteger>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_mults(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFINTEGER";
            desc.properties["ults"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_maxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_maxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["axderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinvok";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineCurve_maxderivinvok(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineCurve_maxderivinvok(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["axderivinvok"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_BezierCurve ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_BezierCurve";
        desc.neo4j_label = "Geom_BezierCurve";
        {
            PropertyDescriptor prop;
            prop.name = "rational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_rational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_rational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["rational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "closed";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_closed(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_closed(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["closed"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "poles";
            prop.type_name = "opencascade::handle<TColgp_HArray1OfPnt>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_poles(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColgp_HArray1OfPnt>&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_poles(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLGP_HARRAY1OFPNT";
            desc.properties["poles"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "weights";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_weights(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_weights(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["weights"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_maxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_maxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["axderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinvok";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierCurve&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierCurve_maxderivinvok(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierCurve&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierCurve_maxderivinvok(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["axderivinvok"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Surface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Surface";
        desc.neo4j_label = "Geom_Surface";
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_Plane ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_Plane";
        desc.neo4j_label = "Geom_Plane";
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_CylindricalSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_CylindricalSurface";
        desc.neo4j_label = "Geom_CylindricalSurface";
        {
            PropertyDescriptor prop;
            prop.name = "radius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_CylindricalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_CylindricalSurface_radius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_CylindricalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_CylindricalSurface_radius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["radius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_ConicalSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_ConicalSurface";
        desc.neo4j_label = "Geom_ConicalSurface";
        {
            PropertyDescriptor prop;
            prop.name = "radius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_ConicalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_ConicalSurface_radius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_ConicalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_ConicalSurface_radius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["radius"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "semiAngle";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_ConicalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_ConicalSurface_semiAngle(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_ConicalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_ConicalSurface_semiAngle(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["semiAngle"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_SphericalSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_SphericalSurface";
        desc.neo4j_label = "Geom_SphericalSurface";
        {
            PropertyDescriptor prop;
            prop.name = "radius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_SphericalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_SphericalSurface_radius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_SphericalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_SphericalSurface_radius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["radius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_ToroidalSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_ToroidalSurface";
        desc.neo4j_label = "Geom_ToroidalSurface";
        {
            PropertyDescriptor prop;
            prop.name = "ajorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_ToroidalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_ToroidalSurface_majorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_ToroidalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_ToroidalSurface_majorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["ajorRadius"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "inorRadius";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_ToroidalSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_ToroidalSurface_minorRadius(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_ToroidalSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_ToroidalSurface_minorRadius(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["inorRadius"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_BSplineSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_BSplineSurface";
        desc.neo4j_label = "Geom_BSplineSurface";
        {
            PropertyDescriptor prop;
            prop.name = "urational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_urational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_urational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["urational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vrational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vrational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vrational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["vrational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "uperiodic";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_uperiodic(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_uperiodic(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["uperiodic"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vperiodic";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vperiodic(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vperiodic(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["vperiodic"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "uknotSet";
            prop.type_name = "GeomAbs_BSplKnotDistribution";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_uknotSet(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_BSplKnotDistribution&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_uknotSet(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_BSPLKNOTDISTRIBUTION";
            desc.properties["uknotSet"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vknotSet";
            prop.type_name = "GeomAbs_BSplKnotDistribution";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vknotSet(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_BSplKnotDistribution&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vknotSet(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_BSPLKNOTDISTRIBUTION";
            desc.properties["vknotSet"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "Usmooth";
            prop.type_name = "GeomAbs_Shape";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_Usmooth(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_Shape&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_Usmooth(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_SHAPE";
            desc.properties["Usmooth"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "Vsmooth";
            prop.type_name = "GeomAbs_Shape";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_Vsmooth(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const GeomAbs_Shape&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_Vsmooth(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GEOMABS_SHAPE";
            desc.properties["Vsmooth"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "udeg";
            prop.type_name = "int";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_udeg(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Integer&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_udeg(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_INT";
            desc.properties["udeg"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vdeg";
            prop.type_name = "int";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vdeg(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Integer&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vdeg(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_INT";
            desc.properties["vdeg"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "poles";
            prop.type_name = "opencascade::handle<TColgp_HArray2OfPnt>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_poles(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColgp_HArray2OfPnt>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_poles(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLGP_HARRAY2OFPNT";
            desc.properties["poles"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "weights";
            prop.type_name = "opencascade::handle<TColStd_HArray2OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_weights(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray2OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_weights(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY2OFREAL";
            desc.properties["weights"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "ufknots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_ufknots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_ufknots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["ufknots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vfknots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vfknots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vfknots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["vfknots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "uknots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_uknots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_uknots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["uknots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vknots";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vknots(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vknots(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFREAL";
            desc.properties["vknots"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "umults";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfInteger>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_umults(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfInteger>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_umults(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFINTEGER";
            desc.properties["umults"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vmults";
            prop.type_name = "opencascade::handle<TColStd_HArray1OfInteger>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vmults(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray1OfInteger>&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vmults(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY1OFINTEGER";
            desc.properties["vmults"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "umaxderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_umaxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_umaxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["umaxderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vmaxderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_vmaxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_vmaxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["vmaxderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinvok";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BSplineSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BSplineSurface_maxderivinvok(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BSplineSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BSplineSurface_maxderivinvok(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["axderivinvok"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering Geom_BezierSurface ---
    {
        TypeDescriptor desc;
        desc.name = "Geom_BezierSurface";
        desc.neo4j_label = "Geom_BezierSurface";
        {
            PropertyDescriptor prop;
            prop.name = "urational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_urational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_urational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["urational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vrational";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_vrational(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_vrational(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["vrational"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "poles";
            prop.type_name = "opencascade::handle<TColgp_HArray2OfPnt>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_poles(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColgp_HArray2OfPnt>&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_poles(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLGP_HARRAY2OFPNT";
            desc.properties["poles"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "weights";
            prop.type_name = "opencascade::handle<TColStd_HArray2OfReal>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_weights(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const opencascade::handle<TColStd_HArray2OfReal>&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_weights(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TCOLSTD_HARRAY2OFREAL";
            desc.properties["weights"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "umaxderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_umaxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_umaxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["umaxderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vmaxderivinv";
            prop.type_name = "double";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_vmaxderivinv(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Real&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_vmaxderivinv(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_DOUBLE";
            desc.properties["vmaxderivinv"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "axderivinvok";
            prop.type_name = "bool";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto* base_ptr = std::any_cast<const Standard_Transient*>(obj_any);
                const auto& obj = static_cast<const Geom_BezierSurface&>(*base_ptr);
                return std::any(ReflectionAccessor::get_Geom_BezierSurface_maxderivinvok(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto* base_ptr = std::any_cast<Standard_Transient*>(obj_any);
                auto& obj = static_cast<Geom_BezierSurface&>(*base_ptr);
                const auto& val = std::any_cast<const Standard_Boolean&>(val_any);
                ReflectionAccessor::set_Geom_BezierSurface_maxderivinvok(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_BOOL";
            desc.properties["axderivinvok"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }
}