// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-11 17:39:08.741965

#include "ManualReflection.h"
#include "ReflectionAccessor.h"

// We must include the headers to have the full type definitions
#include <gp_Pnt.hxx>
#include <gp_Lin.hxx>
#include <gp_XYZ.hxx>
#include <gp_Ax1.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_TShape.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_CompSolid.hxx>
#include <TopoDS_Compound.hxx>
#include <TopoDS_TVertex.hxx>
#include <TopoDS_TEdge.hxx>
#include <TopoDS_TWire.hxx>
#include <TopoDS_TFace.hxx>
#include <TopoDS_TShell.hxx>
#include <TopoDS_TSolid.hxx>
#include <TopoDS_TCompSolid.hxx>
#include <TopoDS_TCompound.hxx>
#include <TopLoc_Location.hxx>

// Implementation of the initialization function declared in ManualReflection.h
void initialize_reflection() {
    auto& registry = ReflectionRegistry::instance();

    // --- Registering gp_Pnt ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Pnt";
        desc.neo4j_label = "gp_Pnt";
        {
            PropertyDescriptor prop;
            prop.name = "coord";
            prop.type_name = "::gp_XYZ";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Pnt&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Pnt_coord(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Pnt&>(obj_any);
                const auto& val = std::any_cast<const ::gp_XYZ&>(val_any);
                ReflectionAccessor::set_gp_Pnt_coord(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_XYZ";
            desc.properties["coord"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Ax1 ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Ax1";
        desc.neo4j_label = "gp_Ax1";
        {
            PropertyDescriptor prop;
            prop.name = "loc";
            prop.type_name = "::gp_Pnt";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax1_loc(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Pnt&>(val_any);
                ReflectionAccessor::set_gp_Ax1_loc(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_PNT";
            desc.properties["loc"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "vdir";
            prop.type_name = "::gp_Dir";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Ax1&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Ax1_vdir(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Ax1&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Dir&>(val_any);
                ReflectionAccessor::set_gp_Ax1_vdir(obj, val);
            };
            desc.properties["vdir"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_XYZ ---
    {
        TypeDescriptor desc;
        desc.name = "gp_XYZ";
        desc.neo4j_label = "gp_XYZ";
        {
            PropertyDescriptor prop;
            prop.name = "x";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_x(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_x(obj, val);
            };
            desc.properties["x"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "y";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_y(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_y(obj, val);
            };
            desc.properties["y"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "z";
            prop.type_name = "::Standard_Real";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_XYZ&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_XYZ_z(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_XYZ&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Real&>(val_any);
                ReflectionAccessor::set_gp_XYZ_z(obj, val);
            };
            desc.properties["z"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering gp_Lin ---
    {
        TypeDescriptor desc;
        desc.name = "gp_Lin";
        desc.neo4j_label = "gp_Lin";
        {
            PropertyDescriptor prop;
            prop.name = "pos";
            prop.type_name = "::gp_Ax1";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const gp_Lin&>(obj_any);
                return std::any(ReflectionAccessor::get_gp_Lin_pos(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<gp_Lin&>(obj_any);
                const auto& val = std::any_cast<const ::gp_Ax1&>(val_any);
                ReflectionAccessor::set_gp_Lin_pos(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_GP_AX1";
            desc.properties["pos"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopLoc_Location ---
    {
        TypeDescriptor desc;
        desc.name = "TopLoc_Location";
        desc.neo4j_label = "TopLoc_Location";
        {
            PropertyDescriptor prop;
            prop.name = "Items";
            prop.type_name = "::TopLoc_SListOfItemLocation";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopLoc_Location&>(obj_any);
                return std::any(ReflectionAccessor::get_TopLoc_Location_myItems(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopLoc_Location&>(obj_any);
                const auto& val = std::any_cast<const ::TopLoc_SListOfItemLocation&>(val_any);
                ReflectionAccessor::set_TopLoc_Location_myItems(obj, val);
            };
            desc.properties["Items"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Shape ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Shape";
        desc.neo4j_label = "TopoDS_Shape";
        {
            PropertyDescriptor prop;
            prop.name = "TShape";
            prop.type_name = "::opencascade::handle<TopoDS_TShape>";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myTShape(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const ::opencascade::handle<TopoDS_TShape>&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myTShape(obj, val);
            };
            desc.properties["TShape"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "Location";
            prop.type_name = "::TopLoc_Location";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myLocation(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const ::TopLoc_Location&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myLocation(obj, val);
            };
            prop.is_relationship = true;
            prop.relationship_name = "HAS_TOPLOC_LOCATION";
            desc.properties["Location"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "Orient";
            prop.type_name = "::TopAbs_Orientation";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_Shape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_Shape_myOrient(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_Shape&>(obj_any);
                const auto& val = std::any_cast<const ::TopAbs_Orientation&>(val_any);
                ReflectionAccessor::set_TopoDS_Shape_myOrient(obj, val);
            };
            desc.properties["Orient"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TShape ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TShape";
        desc.neo4j_label = "TopoDS_TShape";
        {
            PropertyDescriptor prop;
            prop.name = "Shapes";
            prop.type_name = "::TopoDS_ListOfShape";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_TShape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_TShape_myShapes(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_TShape&>(obj_any);
                const auto& val = std::any_cast<const ::TopoDS_ListOfShape&>(val_any);
                ReflectionAccessor::set_TopoDS_TShape_myShapes(obj, val);
            };
            desc.properties["Shapes"] = std::move(prop);
        }
        {
            PropertyDescriptor prop;
            prop.name = "Flags";
            prop.type_name = "::Standard_Integer";
            prop.getter = [] (const std::any& obj_any) -> std::any {
                const auto& obj = std::any_cast<const TopoDS_TShape&>(obj_any);
                return std::any(ReflectionAccessor::get_TopoDS_TShape_myFlags(obj));
            };
            prop.setter = [] (std::any& obj_any, const std::any& val_any) {
                auto& obj = std::any_cast<TopoDS_TShape&>(obj_any);
                const auto& val = std::any_cast<const ::Standard_Integer&>(val_any);
                ReflectionAccessor::set_TopoDS_TShape_myFlags(obj, val);
            };
            desc.properties["Flags"] = std::move(prop);
        }
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Vertex ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Vertex";
        desc.neo4j_label = "TopoDS_Vertex";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Edge ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Edge";
        desc.neo4j_label = "TopoDS_Edge";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Wire ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Wire";
        desc.neo4j_label = "TopoDS_Wire";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Face ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Face";
        desc.neo4j_label = "TopoDS_Face";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Shell ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Shell";
        desc.neo4j_label = "TopoDS_Shell";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Solid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Solid";
        desc.neo4j_label = "TopoDS_Solid";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_CompSolid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_CompSolid";
        desc.neo4j_label = "TopoDS_CompSolid";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_Compound ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_Compound";
        desc.neo4j_label = "TopoDS_Compound";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TVertex ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TVertex";
        desc.neo4j_label = "TopoDS_TVertex";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TEdge ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TEdge";
        desc.neo4j_label = "TopoDS_TEdge";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TWire ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TWire";
        desc.neo4j_label = "TopoDS_TWire";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TFace ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TFace";
        desc.neo4j_label = "TopoDS_TFace";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TShell ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TShell";
        desc.neo4j_label = "TopoDS_TShell";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TSolid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TSolid";
        desc.neo4j_label = "TopoDS_TSolid";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TCompSolid ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TCompSolid";
        desc.neo4j_label = "TopoDS_TCompSolid";
        registry.register_type(std::move(desc));
    }

    // --- Registering TopoDS_TCompound ---
    {
        TypeDescriptor desc;
        desc.name = "TopoDS_TCompound";
        desc.neo4j_label = "TopoDS_TCompound";
        registry.register_type(std::move(desc));
    }
}