#pragma once
// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-11 19:17:53.654445

// --- Forward Declarations for OCCT types ---
class gp_Pnt;
class gp_Dir;
class gp_Ax1;
class gp_Ax2;
class gp_XYZ;
class gp_Trsf;
class gp_Vec;
class gp_Quaternion;
class gp_Ax3;
class TopLoc_Location;
class TopoDS_Shape;
class TopoDS_Vertex;
class TopoDS_Edge;
class TopoDS_Wire;
class TopoDS_Face;
class TopoDS_Shell;
class TopoDS_Solid;
class TopoDS_CompSolid;
class TopoDS_Compound;

// --- Original OCCT Headers ---
#include <gp_Pnt.hxx>
#include <gp_Dir.hxx>
#include <gp_Vec.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Ax3.hxx>
#include <gp_XYZ.hxx>
#include <gp_Trsf.hxx>
#include <gp_Quaternion.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_CompSolid.hxx>
#include <TopoDS_Compound.hxx>
#include <TopLoc_Location.hxx>

class ReflectionAccessor {
public:

    // --- Accessors for gp_Pnt ---
    static const ::gp_XYZ& get_gp_Pnt_coord(const gp_Pnt& obj) { return obj.coord; }
    static void set_gp_Pnt_coord(gp_Pnt& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Dir ---
    static const ::gp_XYZ& get_gp_Dir_coord(const gp_Dir& obj) { return obj.coord; }
    static void set_gp_Dir_coord(gp_Dir& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Ax1 ---
    static const ::gp_Pnt& get_gp_Ax1_loc(const gp_Ax1& obj) { return obj.loc; }
    static void set_gp_Ax1_loc(gp_Ax1& obj, const ::gp_Pnt& value) { obj.loc = value; }
    static const ::gp_Dir& get_gp_Ax1_vdir(const gp_Ax1& obj) { return obj.vdir; }
    static void set_gp_Ax1_vdir(gp_Ax1& obj, const ::gp_Dir& value) { obj.vdir = value; }

    // --- Accessors for gp_Ax2 ---
    static const ::gp_Ax1& get_gp_Ax2_axis(const gp_Ax2& obj) { return obj.axis; }
    static void set_gp_Ax2_axis(gp_Ax2& obj, const ::gp_Ax1& value) { obj.axis = value; }
    static const ::gp_Dir& get_gp_Ax2_vydir(const gp_Ax2& obj) { return obj.vydir; }
    static void set_gp_Ax2_vydir(gp_Ax2& obj, const ::gp_Dir& value) { obj.vydir = value; }
    static const ::gp_Dir& get_gp_Ax2_vxdir(const gp_Ax2& obj) { return obj.vxdir; }
    static void set_gp_Ax2_vxdir(gp_Ax2& obj, const ::gp_Dir& value) { obj.vxdir = value; }

    // --- Accessors for gp_XYZ ---
    static const ::Standard_Real& get_gp_XYZ_x(const gp_XYZ& obj) { return obj.x; }
    static void set_gp_XYZ_x(gp_XYZ& obj, const ::Standard_Real& value) { obj.x = value; }
    static const ::Standard_Real& get_gp_XYZ_y(const gp_XYZ& obj) { return obj.y; }
    static void set_gp_XYZ_y(gp_XYZ& obj, const ::Standard_Real& value) { obj.y = value; }
    static const ::Standard_Real& get_gp_XYZ_z(const gp_XYZ& obj) { return obj.z; }
    static void set_gp_XYZ_z(gp_XYZ& obj, const ::Standard_Real& value) { obj.z = value; }

    // --- Accessors for gp_Trsf ---
    static const ::Standard_Real& get_gp_Trsf_scale(const gp_Trsf& obj) { return obj.scale; }
    static void set_gp_Trsf_scale(gp_Trsf& obj, const ::Standard_Real& value) { obj.scale = value; }
    static const ::gp_TrsfForm& get_gp_Trsf_shape(const gp_Trsf& obj) { return obj.shape; }
    static void set_gp_Trsf_shape(gp_Trsf& obj, const ::gp_TrsfForm& value) { obj.shape = value; }
    static const ::gp_Mat& get_gp_Trsf_matrix(const gp_Trsf& obj) { return obj.matrix; }
    static void set_gp_Trsf_matrix(gp_Trsf& obj, const ::gp_Mat& value) { obj.matrix = value; }
    static const ::gp_XYZ& get_gp_Trsf_loc(const gp_Trsf& obj) { return obj.loc; }
    static void set_gp_Trsf_loc(gp_Trsf& obj, const ::gp_XYZ& value) { obj.loc = value; }

    // --- Accessors for gp_Vec ---
    static const ::gp_XYZ& get_gp_Vec_coord(const gp_Vec& obj) { return obj.coord; }
    static void set_gp_Vec_coord(gp_Vec& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Quaternion ---
    static const ::Standard_Real& get_gp_Quaternion_x(const gp_Quaternion& obj) { return obj.x; }
    static void set_gp_Quaternion_x(gp_Quaternion& obj, const ::Standard_Real& value) { obj.x = value; }
    static const ::Standard_Real& get_gp_Quaternion_y(const gp_Quaternion& obj) { return obj.y; }
    static void set_gp_Quaternion_y(gp_Quaternion& obj, const ::Standard_Real& value) { obj.y = value; }
    static const ::Standard_Real& get_gp_Quaternion_z(const gp_Quaternion& obj) { return obj.z; }
    static void set_gp_Quaternion_z(gp_Quaternion& obj, const ::Standard_Real& value) { obj.z = value; }
    static const ::Standard_Real& get_gp_Quaternion_w(const gp_Quaternion& obj) { return obj.w; }
    static void set_gp_Quaternion_w(gp_Quaternion& obj, const ::Standard_Real& value) { obj.w = value; }

    // --- Accessors for gp_Ax3 ---
    static const ::gp_Ax1& get_gp_Ax3_axis(const gp_Ax3& obj) { return obj.axis; }
    static void set_gp_Ax3_axis(gp_Ax3& obj, const ::gp_Ax1& value) { obj.axis = value; }
    static const ::gp_Dir& get_gp_Ax3_vydir(const gp_Ax3& obj) { return obj.vydir; }
    static void set_gp_Ax3_vydir(gp_Ax3& obj, const ::gp_Dir& value) { obj.vydir = value; }
    static const ::gp_Dir& get_gp_Ax3_vxdir(const gp_Ax3& obj) { return obj.vxdir; }
    static void set_gp_Ax3_vxdir(gp_Ax3& obj, const ::gp_Dir& value) { obj.vxdir = value; }

    // --- Accessors for TopLoc_Location ---
    static const ::TopLoc_SListOfItemLocation& get_TopLoc_Location_myItems(const TopLoc_Location& obj) { return obj.myItems; }
    static void set_TopLoc_Location_myItems(TopLoc_Location& obj, const ::TopLoc_SListOfItemLocation& value) { obj.myItems = value; }

    // --- Accessors for TopoDS_Shape ---
    static const ::opencascade::handle<TopoDS_TShape>& get_TopoDS_Shape_myTShape(const TopoDS_Shape& obj) { return obj.myTShape; }
    static void set_TopoDS_Shape_myTShape(TopoDS_Shape& obj, const ::opencascade::handle<TopoDS_TShape>& value) { obj.myTShape = value; }
    static const ::TopLoc_Location& get_TopoDS_Shape_myLocation(const TopoDS_Shape& obj) { return obj.myLocation; }
    static void set_TopoDS_Shape_myLocation(TopoDS_Shape& obj, const ::TopLoc_Location& value) { obj.myLocation = value; }
    static const ::TopAbs_Orientation& get_TopoDS_Shape_myOrient(const TopoDS_Shape& obj) { return obj.myOrient; }
    static void set_TopoDS_Shape_myOrient(TopoDS_Shape& obj, const ::TopAbs_Orientation& value) { obj.myOrient = value; }

    // --- Accessors for TopoDS_Vertex ---

    // --- Accessors for TopoDS_Edge ---

    // --- Accessors for TopoDS_Wire ---

    // --- Accessors for TopoDS_Face ---

    // --- Accessors for TopoDS_Shell ---

    // --- Accessors for TopoDS_Solid ---

    // --- Accessors for TopoDS_CompSolid ---

    // --- Accessors for TopoDS_Compound ---
};