#pragma once
// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-11 17:39:08.741479

// --- Forward Declarations for OCCT types ---
class gp_Pnt;
class gp_Ax1;
class gp_XYZ;
class gp_Lin;
class TopLoc_Location;
class TopoDS_Shape;
class TopoDS_TShape;
class TopoDS_Vertex;
class TopoDS_Edge;
class TopoDS_Wire;
class TopoDS_Face;
class TopoDS_Shell;
class TopoDS_Solid;
class TopoDS_CompSolid;
class TopoDS_Compound;
class TopoDS_TVertex;
class TopoDS_TEdge;
class TopoDS_TWire;
class TopoDS_TFace;
class TopoDS_TShell;
class TopoDS_TSolid;
class TopoDS_TCompSolid;
class TopoDS_TCompound;

// --- Original OCCT Headers ---
#include <gp_Pnt.hxx>
#include <gp_Lin.hxx>
#include <gp_XYZ.hxx>
#include <gp_Ax1.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_TShape.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_CompSolid.hxx>
#include <TopoDS_Compound.hxx>
#include <TopoDS_TVertex.hxx>
#include <TopoDS_TEdge.hxx>
#include <TopoDS_TWire.hxx>
#include <TopoDS_TFace.hxx>
#include <TopoDS_TShell.hxx>
#include <TopoDS_TSolid.hxx>
#include <TopoDS_TCompSolid.hxx>
#include <TopoDS_TCompound.hxx>
#include <TopLoc_Location.hxx>

class ReflectionAccessor {
public:

    // --- Accessors for gp_Pnt ---
    static const ::gp_XYZ& get_gp_Pnt_coord(const gp_Pnt& obj) { return obj.coord; }
    static void set_gp_Pnt_coord(gp_Pnt& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Ax1 ---
    static const ::gp_Pnt& get_gp_Ax1_loc(const gp_Ax1& obj) { return obj.loc; }
    static void set_gp_Ax1_loc(gp_Ax1& obj, const ::gp_Pnt& value) { obj.loc = value; }
    static const ::gp_Dir& get_gp_Ax1_vdir(const gp_Ax1& obj) { return obj.vdir; }
    static void set_gp_Ax1_vdir(gp_Ax1& obj, const ::gp_Dir& value) { obj.vdir = value; }

    // --- Accessors for gp_XYZ ---
    static const ::Standard_Real& get_gp_XYZ_x(const gp_XYZ& obj) { return obj.x; }
    static void set_gp_XYZ_x(gp_XYZ& obj, const ::Standard_Real& value) { obj.x = value; }
    static const ::Standard_Real& get_gp_XYZ_y(const gp_XYZ& obj) { return obj.y; }
    static void set_gp_XYZ_y(gp_XYZ& obj, const ::Standard_Real& value) { obj.y = value; }
    static const ::Standard_Real& get_gp_XYZ_z(const gp_XYZ& obj) { return obj.z; }
    static void set_gp_XYZ_z(gp_XYZ& obj, const ::Standard_Real& value) { obj.z = value; }

    // --- Accessors for gp_Lin ---
    static const ::gp_Ax1& get_gp_Lin_pos(const gp_Lin& obj) { return obj.pos; }
    static void set_gp_Lin_pos(gp_Lin& obj, const ::gp_Ax1& value) { obj.pos = value; }

    // --- Accessors for TopLoc_Location ---
    static const ::TopLoc_SListOfItemLocation& get_TopLoc_Location_myItems(const TopLoc_Location& obj) { return obj.myItems; }
    static void set_TopLoc_Location_myItems(TopLoc_Location& obj, const ::TopLoc_SListOfItemLocation& value) { obj.myItems = value; }

    // --- Accessors for TopoDS_Shape ---
    static const ::opencascade::handle<TopoDS_TShape>& get_TopoDS_Shape_myTShape(const TopoDS_Shape& obj) { return obj.myTShape; }
    static void set_TopoDS_Shape_myTShape(TopoDS_Shape& obj, const ::opencascade::handle<TopoDS_TShape>& value) { obj.myTShape = value; }
    static const ::TopLoc_Location& get_TopoDS_Shape_myLocation(const TopoDS_Shape& obj) { return obj.myLocation; }
    static void set_TopoDS_Shape_myLocation(TopoDS_Shape& obj, const ::TopLoc_Location& value) { obj.myLocation = value; }
    static const ::TopAbs_Orientation& get_TopoDS_Shape_myOrient(const TopoDS_Shape& obj) { return obj.myOrient; }
    static void set_TopoDS_Shape_myOrient(TopoDS_Shape& obj, const ::TopAbs_Orientation& value) { obj.myOrient = value; }

    // --- Accessors for TopoDS_TShape ---
    static const ::TopoDS_ListOfShape& get_TopoDS_TShape_myShapes(const TopoDS_TShape& obj) { return obj.myShapes; }
    static void set_TopoDS_TShape_myShapes(TopoDS_TShape& obj, const ::TopoDS_ListOfShape& value) { obj.myShapes = value; }
    static const ::Standard_Integer& get_TopoDS_TShape_myFlags(const TopoDS_TShape& obj) { return obj.myFlags; }
    static void set_TopoDS_TShape_myFlags(TopoDS_TShape& obj, const ::Standard_Integer& value) { obj.myFlags = value; }

    // --- Accessors for TopoDS_Vertex ---

    // --- Accessors for TopoDS_Edge ---

    // --- Accessors for TopoDS_Wire ---

    // --- Accessors for TopoDS_Face ---

    // --- Accessors for TopoDS_Shell ---

    // --- Accessors for TopoDS_Solid ---

    // --- Accessors for TopoDS_CompSolid ---

    // --- Accessors for TopoDS_Compound ---

    // --- Accessors for TopoDS_TVertex ---

    // --- Accessors for TopoDS_TEdge ---

    // --- Accessors for TopoDS_TWire ---

    // --- Accessors for TopoDS_TFace ---

    // --- Accessors for TopoDS_TShell ---

    // --- Accessors for TopoDS_TSolid ---

    // --- Accessors for TopoDS_TCompSolid ---

    // --- Accessors for TopoDS_TCompound ---
};