#pragma once
// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-14 21:48:55.270685

// --- Forward Declarations for OCCT types ---
class gp_Pnt;
class gp_Dir;
class gp_Ax1;
class gp_Ax2;
class gp_XYZ;
class gp_Trsf;
class gp_Vec;
class gp_Quaternion;
class gp_Ax3;
class TopLoc_Location;
class TopoDS_Shape;
class TopoDS_Vertex;
class TopoDS_Edge;
class TopoDS_Wire;
class TopoDS_Face;
class TopoDS_Shell;
class TopoDS_Solid;
class TopoDS_CompSolid;
class TopoDS_Compound;
class Geom_Curve;
class Geom_Line;
class Geom_Circle;
class Geom_Ellipse;
class Geom_Hyperbola;
class Geom_Parabola;
class Geom_BSplineCurve;
class Geom_BezierCurve;
class Geom_Surface;
class Geom_Plane;
class Geom_CylindricalSurface;
class Geom_ConicalSurface;
class Geom_SphericalSurface;
class Geom_ToroidalSurface;
class Geom_BSplineSurface;
class Geom_BezierSurface;

// --- Original OCCT Headers ---
#include <gp_Pnt.hxx>
#include <gp_Dir.hxx>
#include <gp_Vec.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Ax3.hxx>
#include <gp_XYZ.hxx>
#include <gp_Trsf.hxx>
#include <gp_Quaternion.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_CompSolid.hxx>
#include <TopoDS_Compound.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Line.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_Hyperbola.hxx>
#include <Geom_Parabola.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_Surface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_BezierSurface.hxx>
#include <TopLoc_Location.hxx>

class ReflectionAccessor {
public:

    // --- Accessors for gp_Pnt ---
    static const ::gp_XYZ& get_gp_Pnt_coord(const gp_Pnt& obj) { return obj.coord; }
    static void set_gp_Pnt_coord(gp_Pnt& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Dir ---
    static const ::gp_XYZ& get_gp_Dir_coord(const gp_Dir& obj) { return obj.coord; }
    static void set_gp_Dir_coord(gp_Dir& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Ax1 ---
    static const ::gp_Pnt& get_gp_Ax1_loc(const gp_Ax1& obj) { return obj.loc; }
    static void set_gp_Ax1_loc(gp_Ax1& obj, const ::gp_Pnt& value) { obj.loc = value; }
    static const ::gp_Dir& get_gp_Ax1_vdir(const gp_Ax1& obj) { return obj.vdir; }
    static void set_gp_Ax1_vdir(gp_Ax1& obj, const ::gp_Dir& value) { obj.vdir = value; }

    // --- Accessors for gp_Ax2 ---
    static const ::gp_Ax1& get_gp_Ax2_axis(const gp_Ax2& obj) { return obj.axis; }
    static void set_gp_Ax2_axis(gp_Ax2& obj, const ::gp_Ax1& value) { obj.axis = value; }
    static const ::gp_Dir& get_gp_Ax2_vydir(const gp_Ax2& obj) { return obj.vydir; }
    static void set_gp_Ax2_vydir(gp_Ax2& obj, const ::gp_Dir& value) { obj.vydir = value; }
    static const ::gp_Dir& get_gp_Ax2_vxdir(const gp_Ax2& obj) { return obj.vxdir; }
    static void set_gp_Ax2_vxdir(gp_Ax2& obj, const ::gp_Dir& value) { obj.vxdir = value; }

    // --- Accessors for gp_XYZ ---
    static const ::Standard_Real& get_gp_XYZ_x(const gp_XYZ& obj) { return obj.x; }
    static void set_gp_XYZ_x(gp_XYZ& obj, const ::Standard_Real& value) { obj.x = value; }
    static const ::Standard_Real& get_gp_XYZ_y(const gp_XYZ& obj) { return obj.y; }
    static void set_gp_XYZ_y(gp_XYZ& obj, const ::Standard_Real& value) { obj.y = value; }
    static const ::Standard_Real& get_gp_XYZ_z(const gp_XYZ& obj) { return obj.z; }
    static void set_gp_XYZ_z(gp_XYZ& obj, const ::Standard_Real& value) { obj.z = value; }

    // --- Accessors for gp_Trsf ---
    static const ::Standard_Real& get_gp_Trsf_scale(const gp_Trsf& obj) { return obj.scale; }
    static void set_gp_Trsf_scale(gp_Trsf& obj, const ::Standard_Real& value) { obj.scale = value; }
    static const ::gp_TrsfForm& get_gp_Trsf_shape(const gp_Trsf& obj) { return obj.shape; }
    static void set_gp_Trsf_shape(gp_Trsf& obj, const ::gp_TrsfForm& value) { obj.shape = value; }
    static const ::gp_Mat& get_gp_Trsf_matrix(const gp_Trsf& obj) { return obj.matrix; }
    static void set_gp_Trsf_matrix(gp_Trsf& obj, const ::gp_Mat& value) { obj.matrix = value; }
    static const ::gp_XYZ& get_gp_Trsf_loc(const gp_Trsf& obj) { return obj.loc; }
    static void set_gp_Trsf_loc(gp_Trsf& obj, const ::gp_XYZ& value) { obj.loc = value; }

    // --- Accessors for gp_Vec ---
    static const ::gp_XYZ& get_gp_Vec_coord(const gp_Vec& obj) { return obj.coord; }
    static void set_gp_Vec_coord(gp_Vec& obj, const ::gp_XYZ& value) { obj.coord = value; }

    // --- Accessors for gp_Quaternion ---
    static const ::Standard_Real& get_gp_Quaternion_x(const gp_Quaternion& obj) { return obj.x; }
    static void set_gp_Quaternion_x(gp_Quaternion& obj, const ::Standard_Real& value) { obj.x = value; }
    static const ::Standard_Real& get_gp_Quaternion_y(const gp_Quaternion& obj) { return obj.y; }
    static void set_gp_Quaternion_y(gp_Quaternion& obj, const ::Standard_Real& value) { obj.y = value; }
    static const ::Standard_Real& get_gp_Quaternion_z(const gp_Quaternion& obj) { return obj.z; }
    static void set_gp_Quaternion_z(gp_Quaternion& obj, const ::Standard_Real& value) { obj.z = value; }
    static const ::Standard_Real& get_gp_Quaternion_w(const gp_Quaternion& obj) { return obj.w; }
    static void set_gp_Quaternion_w(gp_Quaternion& obj, const ::Standard_Real& value) { obj.w = value; }

    // --- Accessors for gp_Ax3 ---
    static const ::gp_Ax1& get_gp_Ax3_axis(const gp_Ax3& obj) { return obj.axis; }
    static void set_gp_Ax3_axis(gp_Ax3& obj, const ::gp_Ax1& value) { obj.axis = value; }
    static const ::gp_Dir& get_gp_Ax3_vydir(const gp_Ax3& obj) { return obj.vydir; }
    static void set_gp_Ax3_vydir(gp_Ax3& obj, const ::gp_Dir& value) { obj.vydir = value; }
    static const ::gp_Dir& get_gp_Ax3_vxdir(const gp_Ax3& obj) { return obj.vxdir; }
    static void set_gp_Ax3_vxdir(gp_Ax3& obj, const ::gp_Dir& value) { obj.vxdir = value; }

    // --- Accessors for TopLoc_Location ---
    static const ::TopLoc_SListOfItemLocation& get_TopLoc_Location_myItems(const TopLoc_Location& obj) { return obj.myItems; }
    static void set_TopLoc_Location_myItems(TopLoc_Location& obj, const ::TopLoc_SListOfItemLocation& value) { obj.myItems = value; }

    // --- Accessors for TopoDS_Shape ---
    static const ::opencascade::handle<TopoDS_TShape>& get_TopoDS_Shape_myTShape(const TopoDS_Shape& obj) { return obj.myTShape; }
    static void set_TopoDS_Shape_myTShape(TopoDS_Shape& obj, const ::opencascade::handle<TopoDS_TShape>& value) { obj.myTShape = value; }
    static const ::TopLoc_Location& get_TopoDS_Shape_myLocation(const TopoDS_Shape& obj) { return obj.myLocation; }
    static void set_TopoDS_Shape_myLocation(TopoDS_Shape& obj, const ::TopLoc_Location& value) { obj.myLocation = value; }
    static const ::TopAbs_Orientation& get_TopoDS_Shape_myOrient(const TopoDS_Shape& obj) { return obj.myOrient; }
    static void set_TopoDS_Shape_myOrient(TopoDS_Shape& obj, const ::TopAbs_Orientation& value) { obj.myOrient = value; }

    // --- Accessors for TopoDS_Vertex ---

    // --- Accessors for TopoDS_Edge ---

    // --- Accessors for TopoDS_Wire ---

    // --- Accessors for TopoDS_Face ---

    // --- Accessors for TopoDS_Shell ---

    // --- Accessors for TopoDS_Solid ---

    // --- Accessors for TopoDS_CompSolid ---

    // --- Accessors for TopoDS_Compound ---

    // --- Accessors for Geom_Curve ---

    // --- Accessors for Geom_Line ---
    static const ::gp_Ax1& get_Geom_Line_pos(const Geom_Line& obj) { return obj.pos; }
    static void set_Geom_Line_pos(Geom_Line& obj, const ::gp_Ax1& value) { obj.pos = value; }

    // --- Accessors for Geom_Circle ---
    static const ::Standard_Real& get_Geom_Circle_radius(const Geom_Circle& obj) { return obj.radius; }
    static void set_Geom_Circle_radius(Geom_Circle& obj, const ::Standard_Real& value) { obj.radius = value; }

    // --- Accessors for Geom_Ellipse ---
    static const ::Standard_Real& get_Geom_Ellipse_majorRadius(const Geom_Ellipse& obj) { return obj.majorRadius; }
    static void set_Geom_Ellipse_majorRadius(Geom_Ellipse& obj, const ::Standard_Real& value) { obj.majorRadius = value; }
    static const ::Standard_Real& get_Geom_Ellipse_minorRadius(const Geom_Ellipse& obj) { return obj.minorRadius; }
    static void set_Geom_Ellipse_minorRadius(Geom_Ellipse& obj, const ::Standard_Real& value) { obj.minorRadius = value; }

    // --- Accessors for Geom_Hyperbola ---
    static const ::Standard_Real& get_Geom_Hyperbola_majorRadius(const Geom_Hyperbola& obj) { return obj.majorRadius; }
    static void set_Geom_Hyperbola_majorRadius(Geom_Hyperbola& obj, const ::Standard_Real& value) { obj.majorRadius = value; }
    static const ::Standard_Real& get_Geom_Hyperbola_minorRadius(const Geom_Hyperbola& obj) { return obj.minorRadius; }
    static void set_Geom_Hyperbola_minorRadius(Geom_Hyperbola& obj, const ::Standard_Real& value) { obj.minorRadius = value; }

    // --- Accessors for Geom_Parabola ---
    static const ::Standard_Real& get_Geom_Parabola_focalLength(const Geom_Parabola& obj) { return obj.focalLength; }
    static void set_Geom_Parabola_focalLength(Geom_Parabola& obj, const ::Standard_Real& value) { obj.focalLength = value; }

    // --- Accessors for Geom_BSplineCurve ---
    static const ::Standard_Boolean& get_Geom_BSplineCurve_rational(const Geom_BSplineCurve& obj) { return obj.rational; }
    static void set_Geom_BSplineCurve_rational(Geom_BSplineCurve& obj, const ::Standard_Boolean& value) { obj.rational = value; }
    static const ::Standard_Boolean& get_Geom_BSplineCurve_periodic(const Geom_BSplineCurve& obj) { return obj.periodic; }
    static void set_Geom_BSplineCurve_periodic(Geom_BSplineCurve& obj, const ::Standard_Boolean& value) { obj.periodic = value; }
    static const ::GeomAbs_BSplKnotDistribution& get_Geom_BSplineCurve_knotSet(const Geom_BSplineCurve& obj) { return obj.knotSet; }
    static void set_Geom_BSplineCurve_knotSet(Geom_BSplineCurve& obj, const ::GeomAbs_BSplKnotDistribution& value) { obj.knotSet = value; }
    static const ::GeomAbs_Shape& get_Geom_BSplineCurve_smooth(const Geom_BSplineCurve& obj) { return obj.smooth; }
    static void set_Geom_BSplineCurve_smooth(Geom_BSplineCurve& obj, const ::GeomAbs_Shape& value) { obj.smooth = value; }
    static const ::Standard_Integer& get_Geom_BSplineCurve_deg(const Geom_BSplineCurve& obj) { return obj.deg; }
    static void set_Geom_BSplineCurve_deg(Geom_BSplineCurve& obj, const ::Standard_Integer& value) { obj.deg = value; }
    static const ::opencascade::handle<TColgp_HArray1OfPnt>& get_Geom_BSplineCurve_poles(const Geom_BSplineCurve& obj) { return obj.poles; }
    static void set_Geom_BSplineCurve_poles(Geom_BSplineCurve& obj, const ::opencascade::handle<TColgp_HArray1OfPnt>& value) { obj.poles = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineCurve_weights(const Geom_BSplineCurve& obj) { return obj.weights; }
    static void set_Geom_BSplineCurve_weights(Geom_BSplineCurve& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.weights = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineCurve_flatknots(const Geom_BSplineCurve& obj) { return obj.flatknots; }
    static void set_Geom_BSplineCurve_flatknots(Geom_BSplineCurve& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.flatknots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineCurve_knots(const Geom_BSplineCurve& obj) { return obj.knots; }
    static void set_Geom_BSplineCurve_knots(Geom_BSplineCurve& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.knots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfInteger>& get_Geom_BSplineCurve_mults(const Geom_BSplineCurve& obj) { return obj.mults; }
    static void set_Geom_BSplineCurve_mults(Geom_BSplineCurve& obj, const ::opencascade::handle<TColStd_HArray1OfInteger>& value) { obj.mults = value; }
    static const ::Standard_Real& get_Geom_BSplineCurve_maxderivinv(const Geom_BSplineCurve& obj) { return obj.maxderivinv; }
    static void set_Geom_BSplineCurve_maxderivinv(Geom_BSplineCurve& obj, const ::Standard_Real& value) { obj.maxderivinv = value; }
    static const ::Standard_Boolean& get_Geom_BSplineCurve_maxderivinvok(const Geom_BSplineCurve& obj) { return obj.maxderivinvok; }
    static void set_Geom_BSplineCurve_maxderivinvok(Geom_BSplineCurve& obj, const ::Standard_Boolean& value) { obj.maxderivinvok = value; }

    // --- Accessors for Geom_BezierCurve ---
    static const ::Standard_Boolean& get_Geom_BezierCurve_rational(const Geom_BezierCurve& obj) { return obj.rational; }
    static void set_Geom_BezierCurve_rational(Geom_BezierCurve& obj, const ::Standard_Boolean& value) { obj.rational = value; }
    static const ::Standard_Boolean& get_Geom_BezierCurve_closed(const Geom_BezierCurve& obj) { return obj.closed; }
    static void set_Geom_BezierCurve_closed(Geom_BezierCurve& obj, const ::Standard_Boolean& value) { obj.closed = value; }
    static const ::opencascade::handle<TColgp_HArray1OfPnt>& get_Geom_BezierCurve_poles(const Geom_BezierCurve& obj) { return obj.poles; }
    static void set_Geom_BezierCurve_poles(Geom_BezierCurve& obj, const ::opencascade::handle<TColgp_HArray1OfPnt>& value) { obj.poles = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BezierCurve_weights(const Geom_BezierCurve& obj) { return obj.weights; }
    static void set_Geom_BezierCurve_weights(Geom_BezierCurve& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.weights = value; }
    static const ::Standard_Real& get_Geom_BezierCurve_maxderivinv(const Geom_BezierCurve& obj) { return obj.maxderivinv; }
    static void set_Geom_BezierCurve_maxderivinv(Geom_BezierCurve& obj, const ::Standard_Real& value) { obj.maxderivinv = value; }
    static const ::Standard_Boolean& get_Geom_BezierCurve_maxderivinvok(const Geom_BezierCurve& obj) { return obj.maxderivinvok; }
    static void set_Geom_BezierCurve_maxderivinvok(Geom_BezierCurve& obj, const ::Standard_Boolean& value) { obj.maxderivinvok = value; }

    // --- Accessors for Geom_Surface ---

    // --- Accessors for Geom_Plane ---

    // --- Accessors for Geom_CylindricalSurface ---
    static const ::Standard_Real& get_Geom_CylindricalSurface_radius(const Geom_CylindricalSurface& obj) { return obj.radius; }
    static void set_Geom_CylindricalSurface_radius(Geom_CylindricalSurface& obj, const ::Standard_Real& value) { obj.radius = value; }

    // --- Accessors for Geom_ConicalSurface ---
    static const ::Standard_Real& get_Geom_ConicalSurface_radius(const Geom_ConicalSurface& obj) { return obj.radius; }
    static void set_Geom_ConicalSurface_radius(Geom_ConicalSurface& obj, const ::Standard_Real& value) { obj.radius = value; }
    static const ::Standard_Real& get_Geom_ConicalSurface_semiAngle(const Geom_ConicalSurface& obj) { return obj.semiAngle; }
    static void set_Geom_ConicalSurface_semiAngle(Geom_ConicalSurface& obj, const ::Standard_Real& value) { obj.semiAngle = value; }

    // --- Accessors for Geom_SphericalSurface ---
    static const ::Standard_Real& get_Geom_SphericalSurface_radius(const Geom_SphericalSurface& obj) { return obj.radius; }
    static void set_Geom_SphericalSurface_radius(Geom_SphericalSurface& obj, const ::Standard_Real& value) { obj.radius = value; }

    // --- Accessors for Geom_ToroidalSurface ---
    static const ::Standard_Real& get_Geom_ToroidalSurface_majorRadius(const Geom_ToroidalSurface& obj) { return obj.majorRadius; }
    static void set_Geom_ToroidalSurface_majorRadius(Geom_ToroidalSurface& obj, const ::Standard_Real& value) { obj.majorRadius = value; }
    static const ::Standard_Real& get_Geom_ToroidalSurface_minorRadius(const Geom_ToroidalSurface& obj) { return obj.minorRadius; }
    static void set_Geom_ToroidalSurface_minorRadius(Geom_ToroidalSurface& obj, const ::Standard_Real& value) { obj.minorRadius = value; }

    // --- Accessors for Geom_BSplineSurface ---
    static const ::Standard_Boolean& get_Geom_BSplineSurface_urational(const Geom_BSplineSurface& obj) { return obj.urational; }
    static void set_Geom_BSplineSurface_urational(Geom_BSplineSurface& obj, const ::Standard_Boolean& value) { obj.urational = value; }
    static const ::Standard_Boolean& get_Geom_BSplineSurface_vrational(const Geom_BSplineSurface& obj) { return obj.vrational; }
    static void set_Geom_BSplineSurface_vrational(Geom_BSplineSurface& obj, const ::Standard_Boolean& value) { obj.vrational = value; }
    static const ::Standard_Boolean& get_Geom_BSplineSurface_uperiodic(const Geom_BSplineSurface& obj) { return obj.uperiodic; }
    static void set_Geom_BSplineSurface_uperiodic(Geom_BSplineSurface& obj, const ::Standard_Boolean& value) { obj.uperiodic = value; }
    static const ::Standard_Boolean& get_Geom_BSplineSurface_vperiodic(const Geom_BSplineSurface& obj) { return obj.vperiodic; }
    static void set_Geom_BSplineSurface_vperiodic(Geom_BSplineSurface& obj, const ::Standard_Boolean& value) { obj.vperiodic = value; }
    static const ::GeomAbs_BSplKnotDistribution& get_Geom_BSplineSurface_uknotSet(const Geom_BSplineSurface& obj) { return obj.uknotSet; }
    static void set_Geom_BSplineSurface_uknotSet(Geom_BSplineSurface& obj, const ::GeomAbs_BSplKnotDistribution& value) { obj.uknotSet = value; }
    static const ::GeomAbs_BSplKnotDistribution& get_Geom_BSplineSurface_vknotSet(const Geom_BSplineSurface& obj) { return obj.vknotSet; }
    static void set_Geom_BSplineSurface_vknotSet(Geom_BSplineSurface& obj, const ::GeomAbs_BSplKnotDistribution& value) { obj.vknotSet = value; }
    static const ::GeomAbs_Shape& get_Geom_BSplineSurface_Usmooth(const Geom_BSplineSurface& obj) { return obj.Usmooth; }
    static void set_Geom_BSplineSurface_Usmooth(Geom_BSplineSurface& obj, const ::GeomAbs_Shape& value) { obj.Usmooth = value; }
    static const ::GeomAbs_Shape& get_Geom_BSplineSurface_Vsmooth(const Geom_BSplineSurface& obj) { return obj.Vsmooth; }
    static void set_Geom_BSplineSurface_Vsmooth(Geom_BSplineSurface& obj, const ::GeomAbs_Shape& value) { obj.Vsmooth = value; }
    static const ::Standard_Integer& get_Geom_BSplineSurface_udeg(const Geom_BSplineSurface& obj) { return obj.udeg; }
    static void set_Geom_BSplineSurface_udeg(Geom_BSplineSurface& obj, const ::Standard_Integer& value) { obj.udeg = value; }
    static const ::Standard_Integer& get_Geom_BSplineSurface_vdeg(const Geom_BSplineSurface& obj) { return obj.vdeg; }
    static void set_Geom_BSplineSurface_vdeg(Geom_BSplineSurface& obj, const ::Standard_Integer& value) { obj.vdeg = value; }
    static const ::opencascade::handle<TColgp_HArray2OfPnt>& get_Geom_BSplineSurface_poles(const Geom_BSplineSurface& obj) { return obj.poles; }
    static void set_Geom_BSplineSurface_poles(Geom_BSplineSurface& obj, const ::opencascade::handle<TColgp_HArray2OfPnt>& value) { obj.poles = value; }
    static const ::opencascade::handle<TColStd_HArray2OfReal>& get_Geom_BSplineSurface_weights(const Geom_BSplineSurface& obj) { return obj.weights; }
    static void set_Geom_BSplineSurface_weights(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray2OfReal>& value) { obj.weights = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineSurface_ufknots(const Geom_BSplineSurface& obj) { return obj.ufknots; }
    static void set_Geom_BSplineSurface_ufknots(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.ufknots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineSurface_vfknots(const Geom_BSplineSurface& obj) { return obj.vfknots; }
    static void set_Geom_BSplineSurface_vfknots(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.vfknots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineSurface_uknots(const Geom_BSplineSurface& obj) { return obj.uknots; }
    static void set_Geom_BSplineSurface_uknots(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.uknots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfReal>& get_Geom_BSplineSurface_vknots(const Geom_BSplineSurface& obj) { return obj.vknots; }
    static void set_Geom_BSplineSurface_vknots(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfReal>& value) { obj.vknots = value; }
    static const ::opencascade::handle<TColStd_HArray1OfInteger>& get_Geom_BSplineSurface_umults(const Geom_BSplineSurface& obj) { return obj.umults; }
    static void set_Geom_BSplineSurface_umults(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfInteger>& value) { obj.umults = value; }
    static const ::opencascade::handle<TColStd_HArray1OfInteger>& get_Geom_BSplineSurface_vmults(const Geom_BSplineSurface& obj) { return obj.vmults; }
    static void set_Geom_BSplineSurface_vmults(Geom_BSplineSurface& obj, const ::opencascade::handle<TColStd_HArray1OfInteger>& value) { obj.vmults = value; }
    static const ::Standard_Real& get_Geom_BSplineSurface_umaxderivinv(const Geom_BSplineSurface& obj) { return obj.umaxderivinv; }
    static void set_Geom_BSplineSurface_umaxderivinv(Geom_BSplineSurface& obj, const ::Standard_Real& value) { obj.umaxderivinv = value; }
    static const ::Standard_Real& get_Geom_BSplineSurface_vmaxderivinv(const Geom_BSplineSurface& obj) { return obj.vmaxderivinv; }
    static void set_Geom_BSplineSurface_vmaxderivinv(Geom_BSplineSurface& obj, const ::Standard_Real& value) { obj.vmaxderivinv = value; }
    static const ::Standard_Boolean& get_Geom_BSplineSurface_maxderivinvok(const Geom_BSplineSurface& obj) { return obj.maxderivinvok; }
    static void set_Geom_BSplineSurface_maxderivinvok(Geom_BSplineSurface& obj, const ::Standard_Boolean& value) { obj.maxderivinvok = value; }

    // --- Accessors for Geom_BezierSurface ---
    static const ::Standard_Boolean& get_Geom_BezierSurface_urational(const Geom_BezierSurface& obj) { return obj.urational; }
    static void set_Geom_BezierSurface_urational(Geom_BezierSurface& obj, const ::Standard_Boolean& value) { obj.urational = value; }
    static const ::Standard_Boolean& get_Geom_BezierSurface_vrational(const Geom_BezierSurface& obj) { return obj.vrational; }
    static void set_Geom_BezierSurface_vrational(Geom_BezierSurface& obj, const ::Standard_Boolean& value) { obj.vrational = value; }
    static const ::opencascade::handle<TColgp_HArray2OfPnt>& get_Geom_BezierSurface_poles(const Geom_BezierSurface& obj) { return obj.poles; }
    static void set_Geom_BezierSurface_poles(Geom_BezierSurface& obj, const ::opencascade::handle<TColgp_HArray2OfPnt>& value) { obj.poles = value; }
    static const ::opencascade::handle<TColStd_HArray2OfReal>& get_Geom_BezierSurface_weights(const Geom_BezierSurface& obj) { return obj.weights; }
    static void set_Geom_BezierSurface_weights(Geom_BezierSurface& obj, const ::opencascade::handle<TColStd_HArray2OfReal>& value) { obj.weights = value; }
    static const ::Standard_Real& get_Geom_BezierSurface_umaxderivinv(const Geom_BezierSurface& obj) { return obj.umaxderivinv; }
    static void set_Geom_BezierSurface_umaxderivinv(Geom_BezierSurface& obj, const ::Standard_Real& value) { obj.umaxderivinv = value; }
    static const ::Standard_Real& get_Geom_BezierSurface_vmaxderivinv(const Geom_BezierSurface& obj) { return obj.vmaxderivinv; }
    static void set_Geom_BezierSurface_vmaxderivinv(Geom_BezierSurface& obj, const ::Standard_Real& value) { obj.vmaxderivinv = value; }
    static const ::Standard_Boolean& get_Geom_BezierSurface_maxderivinvok(const Geom_BezierSurface& obj) { return obj.maxderivinvok; }
    static void set_Geom_BezierSurface_maxderivinvok(Geom_BezierSurface& obj, const ::Standard_Boolean& value) { obj.maxderivinvok = value; }
};