// Generated by Tooling/generate_reflection.py
// Timestamp: 2025-11-10 19:47:29.874905

#include "ReflectionAccessor.h"
#include <rttr/registration.h>

RTTR_REGISTRATION {

    // --- Registration for gp_Pnt ---
    rttr::registration::class_<gp_Pnt>("gp_Pnt")
        (rttr::metadata("neo4j_label", "gp_Pnt"))
        .property("coord", &ReflectionAccessor::get_gp_Pnt_coord, &ReflectionAccessor::set_gp_Pnt_coord)
            (rttr::metadata("neo4j_relationship", "HAS_GP_XYZ"))
    ;

    // --- Registration for gp_Ax1 ---
    rttr::registration::class_<gp_Ax1>("gp_Ax1")
        (rttr::metadata("neo4j_label", "gp_Ax1"))
        .property("loc", &ReflectionAccessor::get_gp_Ax1_loc, &ReflectionAccessor::set_gp_Ax1_loc)
            (rttr::metadata("neo4j_relationship", "HAS_GP_PNT"))
        .property("vdir", &ReflectionAccessor::get_gp_Ax1_vdir, &ReflectionAccessor::set_gp_Ax1_vdir)
    ;

    // --- Registration for gp_XYZ ---
    rttr::registration::class_<gp_XYZ>("gp_XYZ")
        (rttr::metadata("neo4j_label", "gp_XYZ"))
        .property("x", &ReflectionAccessor::get_gp_XYZ_x, &ReflectionAccessor::set_gp_XYZ_x)
        .property("y", &ReflectionAccessor::get_gp_XYZ_y, &ReflectionAccessor::set_gp_XYZ_y)
        .property("z", &ReflectionAccessor::get_gp_XYZ_z, &ReflectionAccessor::set_gp_XYZ_z)
    ;

    // --- Registration for gp_Lin ---
    rttr::registration::class_<gp_Lin>("gp_Lin")
        (rttr::metadata("neo4j_label", "gp_Lin"))
        .property("pos", &ReflectionAccessor::get_gp_Lin_pos, &ReflectionAccessor::set_gp_Lin_pos)
            (rttr::metadata("neo4j_relationship", "HAS_GP_AX1"))
    ;
}