version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: my_neo4j_container # 可以自定义容器名
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    # 为了数据持久化，强烈建议添加 volumes
    # volumes:
    #   - neo4j_data:/data
    #   - neo4j_logs:/logs
    #   - neo4j_import:/var/lib/neo4j/import
    #   - neo4j_plugins:/plugins

# 定义 Docker 卷，用于持久化数据
# volumes:
#   neo4j_data:
#   neo4j_logs:
#   neo4j_import:
#   neo4j_plugins: