import os
from pygccxml import declarations, utils, parser
from datetime import datetime
import config
from gen_run_castxml import read_header_list
from gen_generate_accessor import find_classes_in_xml


def generate_rttr_registration():
    """
    解析 XML 文件并生成 RTTR_Registration.cpp
    """
    print("--- [Module 4] Generating RTTR Registration Code ---")
    if not os.path.exists(config.XML_FILE_PATH):
        print(f"Error: XML file not found at {config.XML_FILE_PATH}. Please run CastXML first.")
        return False

    # --- 1. 解析 XML 文件 ---
    try:
        generator_path, generator_name = utils.find_xml_generator()
        xml_config = parser.xml_generator_configuration_t(
            xml_generator_path=generator_path,
            xml_generator=generator_name,
            include_paths=[config.MIRRORED_DIR, config.OCCT_INC_PATH],
            compiler_path=config.COMPILER_PATH,
            cflags="-std=c++17 -DHAVE_RTTI -DHAVE_CPP11 -DOCC_CONVERT_SIGNALS"
        )

        decls = parser.parse_xml_file(config.XML_FILE_PATH, xml_config)
        global_ns = declarations.get_global_namespace(decls)

    except Exception as e:
        print(f"Error parsing XML file: {e}")
        return False

    headers_to_process = read_header_list()
    classes_to_reflect = find_classes_in_xml(global_ns, headers_to_process)
    class_name_set = {cls.name for cls in classes_to_reflect}

    cpp_lines = [
        '// Generated by Tooling/gen_generate_rttr.py',
        f'// Timestamp: {datetime.now()}',
        '',
        '#include "ReflectionAccessor.h"',
        '#include <rttr/registration.h>',
        '',
        'RTTR_REGISTRATION {',
    ]

    for cls in classes_to_reflect:
        class_name = cls.name

        # --- 过滤模板类、STL类、空名字 ---
        if '<' in class_name or 'std::' in class_name or not class_name.strip():
            continue

        cpp_lines.append(f'\n    // --- Registration for {class_name} ---')
        cpp_lines.append(f'    rttr::registration::class_<{class_name}>("{class_name}")')
        cpp_lines.append(f'        (rttr::metadata("neo4j_label", "{class_name}"))')

        for var in cls.variables():
            if var.name.startswith('the') or var.access_type != 'private':
                continue

            var_name = var.name
            func_name_suffix = f"{class_name}_{var_name}"

            # 属性名去掉前缀 my，如果为空就保留原名
            prop_name = var_name.lstrip('my')
            if not prop_name:
                prop_name = var_name

            accessor_funcs = f"&{config.ACCESSOR_CLASS_NAME}::get_{func_name_suffix}, &{config.ACCESSOR_CLASS_NAME}::set_{func_name_suffix}"

            prop_line = f'        .property("{prop_name}", {accessor_funcs})'

            # --- 推断与其他注册类的关系 ---
            var_type_clean = declarations.remove_const(var.decl_type).decl_string.replace(" &", "")
            if var_type_clean in class_name_set:
                relationship_name = f"HAS_{var_type_clean.upper()}"
                prop_line += f'\n            (rttr::metadata("neo4j_relationship", "{relationship_name}"))'

            cpp_lines.append(prop_line)

        cpp_lines.append('    ;')

    cpp_lines.append('}')

    # 4. 写入文件
    try:
        with open(config.RTTR_CPP_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cpp_lines))
        print(f"Successfully generated {config.RTTR_CPP_FILE}")
        return True
    except Exception as e:
        print(f"Error writing to {config.RTTR_CPP_FILE}: {e}")
        return False


if __name__ == '__main__':
    if not generate_rttr_registration():
        exit(1)
