#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 ReflectionAccessor.h
依赖于先生成好的 CastXML XML 文件（通过 gen_run_castxml.py）
"""

import os
from datetime import datetime
import config

from pygccxml import parser, declarations, utils


def find_classes_in_xml(global_ns, headers_to_process):
    """从 XML 中自动发现指定头文件里的类"""
    found_classes = []
    target_headers = {os.path.normpath(os.path.join(config.MIRRORED_DIR, h)) for h in headers_to_process}

    for cls in global_ns.classes():
        if cls.location:
            cls_file_path = os.path.normpath(cls.location.file_name)
            if cls_file_path in target_headers:
                found_classes.append(cls)
    return found_classes


def generate_accessor():
    print("--- [Module 3] Generating Accessor Header ---")

    if not os.path.exists(config.XML_FILE_PATH):
        print(f"Error: XML file not found at {config.XML_FILE_PATH}. Please run gen_run_castxml.py first.")
        return False

    # --- 1. 解析 XML 文件 ---
    try:
        # 查找 CastXML
        generator_path, generator_name = utils.find_xml_generator()
        xml_config = parser.xml_generator_configuration_t(
            xml_generator_path=generator_path,
            xml_generator=generator_name,
            include_paths=[config.MIRRORED_DIR, config.OCCT_INC_PATH],
            compiler_path=config.COMPILER_PATH,
            cflags="-std=c++17 -DHAVE_RTTI -DHAVE_CPP11 -DOCC_CONVERT_SIGNALS"
        )

        decls = parser.parse_xml_file(config.XML_FILE_PATH, xml_config)
        global_ns = declarations.get_global_namespace(decls)

    except Exception as e:
        print(f"Error parsing XML file: {e}")
        return False

    # --- 2. 读取 headers 列表 ---
    from gen_run_castxml import read_header_list
    headers_to_process = read_header_list()

    # --- 3. 自动发现类 ---
    classes_to_reflect = find_classes_in_xml(global_ns, headers_to_process)
    if not classes_to_reflect:
        print("Warning: No classes found in the specified headers. Accessor file will be empty.")

    # --- 4. 准备 header 文件内容 ---
    header_lines = [
        '#pragma once',
        '// Generated by Tooling/gen_generate_accessor.py',
        f'// Timestamp: {datetime.now()}',
        '',
        '#include <rttr/type>',
        '// --- Include Original OCCT Headers ---',
    ]

    for header in headers_to_process:
        header_lines.append(f'#include <{os.path.basename(header)}>')

    header_lines.extend([
        '',
        f'class {config.ACCESSOR_CLASS_NAME} {{',
        'public:'
    ])

    # --- 5. 为每个类生成 getter/setter ---
    for cls in classes_to_reflect:
        class_name = cls.name
        header_lines.append(f'\n    // --- Accessors for {class_name} ---')

        try:
            for var in cls.variables(allow_empty=True):
                # 过滤掉不需要反射的成员
                if var.name.startswith('the') or var.access_type != 'private':
                    continue

                var_type_str = var.decl_type.decl_string
                var_name = var.name
                func_name_suffix = f"{class_name}_{var_name}"

                header_lines.append(
                    f"    static const {var_type_str}& get_{func_name_suffix}(const {class_name}& obj) {{ return obj.{var_name}; }}")
                header_lines.append(
                    f"    static void set_{func_name_suffix}({class_name}& obj, const {var_type_str}& value) {{ obj.{var_name} = value; }}")
        except RuntimeError as e:
            print(f"Warning: Could not process variables of class {class_name}: {e}")
            continue

    header_lines.append('};')

    # --- 6. 写入文件 ---
    try:
        with open(config.ACCESSOR_H_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(header_lines))
        print(f"Successfully generated {config.ACCESSOR_H_FILE}")
        return True
    except Exception as e:
        print(f"Error writing to {config.ACCESSOR_H_FILE}: {e}")
        return False


if __name__ == '__main__':
    if not generate_accessor():
        exit(1)
